#!/usr/bin/env bash
# Generates Command-Reference.md for the macos-scripts GitHub Wiki.
# Run from anywhere: ./tools/scripts/generate-wiki-command-ref.sh
# Output: ~/macos-scripts.wiki/Command-Reference.md

set -euo pipefail

BASE_DIR="${MACOS_SCRIPTS_HOME:-$HOME/macos-scripts}"
WIKI_DIR="$HOME/macos-scripts.wiki"
OUTPUT="$WIKI_DIR/Command-Reference.md"

# ── helpers ────────────────────────────────────────────────────────────────

# Decides whether a candidate is publishable description text.
#
# An unexpanded shell variable is never a description: the published page once
# carried a literal `$dashboard` for ui/terminal-ui/mq-ui.sh, matched out of
# `print_dashboard_header "$dashboard"`. Rule 1 below was supposed to guard
# against that for APP_NAME, but its sed only *fails to match* a value like
# "$title" — and an unmatched sed prints the line unchanged, so the whole
# `APP_NAME="$title"` line was kept rather than dropped. The check has to be its
# own step, applied to every rule.
accept_title() {
  local candidate="$1"

  [[ -n "$candidate" && ${#candidate} -lt 60 && "$candidate" != *'$'* ]]
}

# Extracts meta from command or file content.
extract_meta() {
  local file="$1"

  # 1. APP_NAME / APP_TITLE
  local title
  title=$(grep -m1 -E '^(APP_NAME|APP_TITLE)=' "$file" 2>/dev/null \
    | sed -E 's/^[A-Z_]+="?([^"#$]+)"?.*/\1/' | xargs || true)
  accept_title "$title" && { printf '%s' "$title"; return; }

  # 2. header "..." call
  title=$(grep -m1 'header "' "$file" 2>/dev/null \
    | sed -E 's/.*header "([^"]+)".*/\1/' | xargs || true)
  accept_title "$title" && { printf '%s' "$title"; return; }

  # 3. Banner line (-- SOMETHING --), as printed by printf/echo in the script's
  # own header art. Despite the old wording these are not comments.
  #
  # Two things were wrong. `--` terminates the option list: the pattern starts
  # with two dashes, so without it grep read the pattern as an option, exited 2,
  # and the rule never fired at all. And the pattern was loose enough to match
  # inside `--- SECTION ---` separators and `<!-- ... -->` markers, which are
  # not titles — requiring the delimiter to be exactly two dashes separates the
  # banner from the separator.
  title=$(grep -m1 -E -- '(^|[^-])-- [A-Z].+ --([^->]|$)' "$file" 2>/dev/null \
    | sed -E 's/.*-- ([A-Z][^-]+) --.*/\1/' | tr -d '"' | xargs || true)
  accept_title "$title" && { printf '%s' "$title"; return; }

  # 4. Usage line (command verb only, not full echo)
  title=$(grep -A1 'Usage:' "$file" 2>/dev/null \
    | grep -m1 'mqlaunch\|mq ' \
    | sed -E 's/^[[:space:]]*//' | xargs || true)
  accept_title "$title" && [[ "$title" != echo* ]] && { printf '%s' "$title"; return; }

  printf ''
}

# Extracts usage from command or file content.
extract_usage() {
  local file="$1"
  # Grab the first command line under a Usage: block
  grep -A2 'Usage:' "$file" 2>/dev/null \
    | grep -m1 -E '^\s+(mqlaunch|mq |\.\/|tools/)' \
    | sed -E 's/^[[:space:]]*//' || true
}

# Coordinates category label behavior.
category_label() {
  local rel="$1"
  case "$rel" in
    terminal/launchers/*)    printf 'Launchers' ;;
    terminal/menus/*)        printf 'Menus' ;;
    terminal/release/*)      printf 'Release' ;;
    terminal/ai-prompts/*)   printf 'AI Prompts' ;;
    terminal/themes/*)       printf 'Themes' ;;
    terminal/bridges/*)      printf 'Bridges' ;;
    tools/scripts/*)         printf 'Tools & Scripts' ;;
    tools/cli/*)             printf 'CLI Library' ;;
    automation/*)            printf 'Automation' ;;
    system/*)                printf 'System' ;;
    ui/*)                    printf 'UI' ;;
    *)                       printf 'Other' ;;
  esac
}

# Coordinates should skip behavior.
should_skip() {
  local rel="$1"
  case "$rel" in
    tools/legacy/*)                          return 0 ;;
    backups/*)                               return 0 ;;
    tools/scripts/generate-wiki-command-ref*) return 0 ;;
    *)                                        return 1 ;;
  esac
}

# ── collect data ───────────────────────────────────────────────────────────

declare -A cat_rows  # category → accumulated table rows

while IFS= read -r file; do
  rel="${file#$BASE_DIR/}"
  should_skip "$rel" && continue

  name=$(basename "$file" .sh)
  category=$(category_label "$rel")
  desc=$(extract_meta "$file")
  usage=$(extract_usage "$file")

  row="| \`$name\` | ${desc:-—} | \`${usage:-—}\` | [\`$rel\`](../$rel) |"
  cat_rows["$category"]+="$row"$'\n'

done < <(find "$BASE_DIR" -name '*.sh' -not -path '*/.git/*' | sort)

# ── write output ───────────────────────────────────────────────────────────

mkdir -p "$WIKI_DIR"

{
  printf '# Command Reference\n\n'
  printf '_Auto-generated by `tools/scripts/generate-wiki-command-ref.sh` — do not edit manually._\n\n'
  printf '%s\n\n' '---'

  for category in Launchers Menus "AI Prompts" Themes Bridges "Release" \
                  "Tools & Scripts" "CLI Library" Automation System UI Other; do
    rows="${cat_rows[$category]:-}"
    [[ -z "$rows" ]] && continue

    printf '## %s\n\n' "$category"
    printf '| Script | Description | Usage | Path |\n'
    printf '|---|---|---|---|\n'
    printf '%s' "$rows"
    printf '\n'
  done

  printf '%s\n\n' '---'
  printf '_Generated: %s_\n' "$(date '+%Y-%m-%d %H:%M')"
} > "$OUTPUT"

printf '[ok] Written: %s\n' "$OUTPUT"
wc -l < "$OUTPUT" | xargs printf '[ok] Lines: %s\n'
