#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="${MACOS_SCRIPTS_HOME:-$HOME/macos-scripts}"
ROOT="$PROJECT_ROOT/tools/scripts"

: "${PYTHONPYCACHEPREFIX:=${TMPDIR:-/tmp}/macos-scripts-pycache}"
export PYTHONPYCACHEPREFIX
mkdir -p "$PYTHONPYCACHEPREFIX"

echo "== Running mqlaunch legacy/bridge checks =="
"$ROOT/test-mqlaunch.sh"

echo
echo "== Running mqlaunch headless checks =="
"$PROJECT_ROOT/tests/headless-smoke.sh"
"$PROJECT_ROOT/tests/git-status-contract-smoke.sh"
"$PROJECT_ROOT/tests/runtime-authority-freeze-smoke.sh"
"$PROJECT_ROOT/tests/hal-args-no-eval-smoke.sh"
"$PROJECT_ROOT/tests/mq-debug-smoke.sh"
"$PROJECT_ROOT/tests/monolith-delayer-smoke.sh"
"$PROJECT_ROOT/tests/theme-command-surface-smoke.sh"
"$PROJECT_ROOT/tests/theme-lib-smoke.sh"
"$PROJECT_ROOT/tests/panel-color-smoke.sh"
"$PROJECT_ROOT/tests/prompt-lib-smoke.sh"
"$PROJECT_ROOT/tests/ui-spinner-smoke.sh"
bash "$PROJECT_ROOT/tests/ui-progress-result-smoke.sh"
"$PROJECT_ROOT/tests/mq-stack-contract-smoke.sh"
"$PROJECT_ROOT/tests/gitlaunch-menu-surface-smoke.sh"
"$PROJECT_ROOT/tests/gitlaunch-pr-push-recovery-smoke.sh"
"$PROJECT_ROOT/tests/gitmerge-safe-smoke.sh"
"$PROJECT_ROOT/tests/gitpr-merge-safe-smoke.sh"
"$PROJECT_ROOT/tests/git-menu-surface-smoke.sh"
"$PROJECT_ROOT/tests/git-restore-to-base-smoke.sh"
"$PROJECT_ROOT/tests/dashboard-header-cache-smoke.sh"
"$PROJECT_ROOT/tests/command-docs-smoke.sh"
"$PROJECT_ROOT/tests/docs-file-inventory-smoke.sh"
"$PROJECT_ROOT/tests/unknown-command-contract-smoke.sh"
"$PROJECT_ROOT/tests/namespace-help-smoke.sh"
"$PROJECT_ROOT/tests/delegated-exit-code-smoke.sh"
"$PROJECT_ROOT/tests/menu-exit-contract-smoke.sh"
"$PROJECT_ROOT/tests/theme-manager-path-smoke.sh"
"$PROJECT_ROOT/tests/runtime-authority-classification-smoke.sh"
"$PROJECT_ROOT/tests/compat-path-delegation-smoke.sh"
"$PROJECT_ROOT/tests/plain-output-contract-smoke.sh"
"$PROJECT_ROOT/tests/netpulse-cli-color-contract-smoke.sh"
"$PROJECT_ROOT/tests/pulse-contract-smoke.sh"
"$PROJECT_ROOT/tests/pulse-collectors-smoke.sh"
"$PROJECT_ROOT/tests/pulse-state-collectors-smoke.sh"
"$PROJECT_ROOT/tests/pulse-attention-smoke.sh"
"$PROJECT_ROOT/tests/pulse-menu-smoke.sh"
"$PROJECT_ROOT/tests/pulse-machine-surface-smoke.sh"
"$PROJECT_ROOT/tests/pulse-degradation-smoke.sh"
"$PROJECT_ROOT/tests/pulse-git-concurrency-smoke.sh"
"$PROJECT_ROOT/tests/next-contract-smoke.sh"
"$PROJECT_ROOT/tests/next-command-smoke.sh"
"$PROJECT_ROOT/tests/branch-supersede-smoke.sh"
"$PROJECT_ROOT/tests/theme-exact-sync-smoke.sh"
"$PROJECT_ROOT/tests/operator-usage-message-smoke.sh"
"$PROJECT_ROOT/tests/doctor-status-contract-smoke.sh"
"$PROJECT_ROOT/tests/apps-menu-surface-smoke.sh"
"$PROJECT_ROOT/tests/delegate-missing-message-smoke.sh"
"$PROJECT_ROOT/tests/command-registry-smoke.sh"
"$PROJECT_ROOT/tests/output-mode-parity-smoke.sh"
"$PROJECT_ROOT/tests/registry-consumer-parity-smoke.sh"
"$PROJECT_ROOT/tests/menu-eof-smoke.sh"
"$PROJECT_ROOT/tests/command-word-normalization-smoke.sh"
"$PROJECT_ROOT/tests/release-check-contract-smoke.sh"
"$PROJECT_ROOT/tests/release-secret-scan-smoke.sh"
"$PROJECT_ROOT/tests/release-pull-request-mode-smoke.sh"
"$PROJECT_ROOT/tests/wiki-command-ref-smoke.sh"
"$PROJECT_ROOT/tests/terminal-width-smoke.sh"
"$PROJECT_ROOT/tests/mq-git-protected-push-smoke.sh"
"$PROJECT_ROOT/tests/test-inventory-smoke.sh"
"$PROJECT_ROOT/tests/install-contract-smoke.sh"
"$PROJECT_ROOT/tests/performance-screens-golden-smoke.sh"
"$PROJECT_ROOT/tests/markdownlint-routing-smoke.sh"
"$PROJECT_ROOT/tests/mq-flow-routing-smoke.sh"
"$PROJECT_ROOT/tests/mq-obsidian-menu-no-promotion-smoke.sh"
"$PROJECT_ROOT/tests/mq-obsidian-python-smoke.sh"
"$PROJECT_ROOT/tests/mqobsidian-manifest-shell-parity-smoke.sh"
"$PROJECT_ROOT/tests/mq-obsidian-regenerate-placeholder-ui-smoke.sh"
"$PROJECT_ROOT/tests/mq-obsidian-regenerate-views-smoke.sh"
"$PROJECT_ROOT/tests/mq-obsidian-triage-ui-smoke.sh"
"$PROJECT_ROOT/tests/brain-bridge-smoke.sh"
"$PROJECT_ROOT/tests/system-menu-smoke.sh"
"$PROJECT_ROOT/tests/dev-menu-smoke.sh"
"$PROJECT_ROOT/tests/menu-shell-guard-smoke.sh"
"$PROJECT_ROOT/tests/release-menu-smoke.sh"
"$PROJECT_ROOT/tests/skills-repos-smoke.sh"
"$PROJECT_ROOT/tests/mq-agent-routing-smoke.sh"
"$PROJECT_ROOT/tests/mq-route-entrypoint-smoke.sh"
"$PROJECT_ROOT/tests/mq-memory-cochange-routing-smoke.sh"
"$PROJECT_ROOT/tests/mq-obsidian-command-routes-smoke.sh"

echo
echo "== Running HAL menu checks =="
"$PROJECT_ROOT/tests/hal-menu-smoke.sh"
"$PROJECT_ROOT/tests/hal-menu-layout-smoke.sh"
"$PROJECT_ROOT/tests/hal-command-surface-smoke.sh"
"$PROJECT_ROOT/tests/hal-format-smoke.sh"
"$PROJECT_ROOT/tests/hal-gallery-smoke.sh"
"$PROJECT_ROOT/tests/hal-pages-smoke.sh"
"$PROJECT_ROOT/tests/hal-screenshot-smoke.sh"
"$PROJECT_ROOT/tests/pages-index-smoke.sh"
"$PROJECT_ROOT/tests/workflows-validation-smoke.sh"
"$PROJECT_ROOT/tests/document-functions-quality-smoke.sh"
"$PROJECT_ROOT/tests/ollama-document-review-smoke.sh"
"$PROJECT_ROOT/tests/command-discovery-inventory-smoke.sh"

echo
echo "== Running shell lint checks =="
bash "$ROOT/lint.sh"

echo
echo "[PASS] All selftest checks passed."
