#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="${MACOS_SCRIPTS_HOME:-$HOME/macos-scripts}"
ROOT="$PROJECT_ROOT/tools/scripts"

: "${PYTHONPYCACHEPREFIX:=${TMPDIR:-/tmp}/macos-scripts-pycache}"
export PYTHONPYCACHEPREFIX
mkdir -p "$PYTHONPYCACHEPREFIX"

echo "== Running mqlaunch legacy/bridge checks =="
"$ROOT/test-mqlaunch.sh"

echo
echo "== Running mqlaunch headless checks =="
"$PROJECT_ROOT/tests/headless-smoke.sh"
"$PROJECT_ROOT/tests/git-status-contract-smoke.sh"
"$PROJECT_ROOT/tests/runtime-authority-freeze-smoke.sh"
"$PROJECT_ROOT/tests/hal-args-no-eval-smoke.sh"
"$PROJECT_ROOT/tests/mq-debug-smoke.sh"
"$PROJECT_ROOT/tests/monolith-delayer-smoke.sh"
"$PROJECT_ROOT/tests/theme-lib-smoke.sh"
"$PROJECT_ROOT/tests/panel-color-smoke.sh"
"$PROJECT_ROOT/tests/prompt-lib-smoke.sh"
"$PROJECT_ROOT/tests/mq-stack-contract-smoke.sh"
"$PROJECT_ROOT/tests/gitmerge-safe-smoke.sh"
"$PROJECT_ROOT/tests/git-restore-to-base-smoke.sh"
"$PROJECT_ROOT/tests/dashboard-header-cache-smoke.sh"
"$PROJECT_ROOT/tests/command-docs-smoke.sh"
"$PROJECT_ROOT/tests/docs-file-inventory-smoke.sh"
"$PROJECT_ROOT/tests/unknown-command-contract-smoke.sh"
"$PROJECT_ROOT/tests/namespace-help-smoke.sh"
"$PROJECT_ROOT/tests/delegated-exit-code-smoke.sh"
"$PROJECT_ROOT/tests/runtime-authority-classification-smoke.sh"
"$PROJECT_ROOT/tests/compat-path-delegation-smoke.sh"
"$PROJECT_ROOT/tests/plain-output-contract-smoke.sh"
"$PROJECT_ROOT/tests/doctor-status-contract-smoke.sh"
"$PROJECT_ROOT/tests/command-registry-smoke.sh"
"$PROJECT_ROOT/tests/output-mode-parity-smoke.sh"
"$PROJECT_ROOT/tests/registry-consumer-parity-smoke.sh"
"$PROJECT_ROOT/tests/menu-eof-smoke.sh"
"$PROJECT_ROOT/tests/command-word-normalization-smoke.sh"
"$PROJECT_ROOT/tests/release-check-contract-smoke.sh"
"$PROJECT_ROOT/tests/release-pull-request-mode-smoke.sh"
"$PROJECT_ROOT/tests/wiki-command-ref-smoke.sh"
"$PROJECT_ROOT/tests/terminal-width-smoke.sh"
"$PROJECT_ROOT/tests/mq-git-protected-push-smoke.sh"
"$PROJECT_ROOT/tests/test-inventory-smoke.sh"
"$PROJECT_ROOT/tests/markdownlint-routing-smoke.sh"
"$PROJECT_ROOT/tests/mq-flow-routing-smoke.sh"
"$PROJECT_ROOT/tests/mq-obsidian-menu-no-promotion-smoke.sh"
"$PROJECT_ROOT/tests/mq-obsidian-python-smoke.sh"
"$PROJECT_ROOT/tests/mq-obsidian-regenerate-placeholder-ui-smoke.sh"
"$PROJECT_ROOT/tests/mq-obsidian-triage-ui-smoke.sh"
"$PROJECT_ROOT/tests/brain-bridge-smoke.sh"
"$PROJECT_ROOT/tests/system-menu-smoke.sh"
"$PROJECT_ROOT/tests/skills-repos-smoke.sh"
"$PROJECT_ROOT/tests/mq-agent-routing-smoke.sh"
"$PROJECT_ROOT/tests/mq-memory-cochange-routing-smoke.sh"
"$PROJECT_ROOT/tests/mq-obsidian-command-routes-smoke.sh"

echo
echo "== Running HAL menu checks =="
"$PROJECT_ROOT/tests/hal-menu-smoke.sh"
"$PROJECT_ROOT/tests/hal-menu-layout-smoke.sh"
"$PROJECT_ROOT/tests/hal-command-surface-smoke.sh"
"$PROJECT_ROOT/tests/hal-format-smoke.sh"
"$PROJECT_ROOT/tests/hal-gallery-smoke.sh"
"$PROJECT_ROOT/tests/hal-pages-smoke.sh"
"$PROJECT_ROOT/tests/hal-screenshot-smoke.sh"
"$PROJECT_ROOT/tests/pages-index-smoke.sh"
"$PROJECT_ROOT/tests/workflows-validation-smoke.sh"
"$PROJECT_ROOT/tests/document-functions-quality-smoke.sh"
"$PROJECT_ROOT/tests/ollama-document-review-smoke.sh"
"$PROJECT_ROOT/tests/command-discovery-inventory-smoke.sh"

echo
echo "== Running mqlaunch v1 checks =="
bash "$ROOT/test-mqlaunch-v1.sh"

echo
echo "== Running shell lint checks =="
bash "$ROOT/lint.sh"

echo
echo "[PASS] All selftest checks passed."
