#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LEGACY_MENU="$ROOT/terminal/launchers/gitlaunch.sh"
GIT_MENU="$ROOT/terminal/menus/mq-git-menu.sh"
DOCS="$ROOT/docs/COMMANDS.md"

zsh -n "$LEGACY_MENU"
bash -n "$GIT_MENU"

grep -Fq "pr_aware_push" "$LEGACY_MENU"
grep -Fq "pr_aware_push" "$GIT_MENU"
grep -Fq "GH013" "$LEGACY_MENU"
grep -Fq "GH013" "$GIT_MENU"
grep -Fq "MQLAUNCH_PROTECTED_BRANCHES" "$LEGACY_MENU"
grep -Fq "MQLAUNCH_PROTECTED_BRANCHES" "$GIT_MENU"
grep -Fq "run_ai_commit" "$LEGACY_MENU"
grep -Fq "pause_git_menu" "$LEGACY_MENU"
grep -Fq "run_ai_commit" "$LEGACY_MENU" && grep -Fq "continue" "$LEGACY_MENU"
grep -Fq "mark_gitlaunch_back" "$LEGACY_MENU"
grep -Fq "BACK_MARKER" "$LEGACY_MENU"
grep -Fq "MQ_GITLAUNCH_BACK_MARKER" "$LEGACY_MENU"
grep -Fq "gitlaunch_terminal_width" "$LEGACY_MENU"
grep -Fq "update_ui_width" "$LEGACY_MENU"
grep -Fq "width > 112" "$LEGACY_MENU"
grep -Fq "width < 60" "$LEGACY_MENU"
grep -Fq "refresh_git_counters" "$LEGACY_MENU"
grep -Fq "9. Recent log" "$LEGACY_MENU"
grep -Fq "show_recent_log" "$LEGACY_MENU"
grep -Fq "Staged:" "$LEGACY_MENU"
grep -Fq "if [[ -t 0 && -t 1 ]]" "$LEGACY_MENU"
grep -Fq "PR branch" "$DOCS"

echo "mq git protected-push smoke OK"
