#!/usr/bin/env bash
set -euo pipefail

# Same resolution as tools/scripts/doctor.sh, tools/scripts/scan.sh and — since
# #172 — mq-zsh-theme-switcher.sh, which carried this identical line. Reading
# `${HOME}/macos-scripts` outright meant `preview` could not run from a checkout
# anywhere else: it died sourcing a UI library that was not there. The other
# four verbs never touch BASE_DIR, which is why the defect stayed invisible.
BASE_DIR="${MACOS_SCRIPTS_HOME:-$HOME/macos-scripts}"
UI_LIB="$BASE_DIR/ui/terminal-ui/mq-ui.sh"
# Not BASE_DIR. The selected theme is user state, the same class as ~/.zshrc,
# and belongs in $HOME wherever the checkout lives.
THEME_FILE="${HOME}/.mq-theme"
SYNC_LIB="$BASE_DIR/terminal/themes/mq-theme-sync.sh"
PROMPT_THEME_SCRIPT="$BASE_DIR/terminal/themes/mq-zsh-theme-switcher.sh"

if [[ -f "$SYNC_LIB" ]]; then
  # shellcheck disable=SC1090
  source "$SYNC_LIB"
fi

# Handles theme list.
theme_list() {
  cat <<'LIST'
classic
green
amber
ice
synth
LIST
}

# Handles theme description.
theme_description() {
  case "$1" in
    classic) echo "Yellow/blue MQ default feel" ;;
    green)   echo "Green terminal vibe" ;;
    amber)   echo "Warm amber monitor feel" ;;
    ice)     echo "Cool cyan/blue theme" ;;
    synth)   echo "Purple neon style" ;;
    *)       return 1 ;;
  esac
}

# Handles theme exports.
theme_exports() {
  case "$1" in
    classic)
      cat <<'EOF_THEME'
export MQ_THEME_NAME="classic"
export MQ_COLOR_TITLE=$'\033[1;33m'
export MQ_COLOR_ERR=$'\033[0;31m'
export MQ_COLOR_OK=$'\033[0;32m'
export MQ_COLOR_WARN=$'\033[0;33m'
export MQ_COLOR_INFO=$'\033[0;34m'
export MQ_COLOR_BOLD=$'\033[1m'
EOF_THEME
      ;;
    green)
      cat <<'EOF_THEME'
export MQ_THEME_NAME="green"
export MQ_COLOR_TITLE=$'\033[1;32m'
export MQ_COLOR_ERR=$'\033[0;31m'
export MQ_COLOR_OK=$'\033[1;32m'
export MQ_COLOR_WARN=$'\033[0;33m'
export MQ_COLOR_INFO=$'\033[0;32m'
export MQ_COLOR_BOLD=$'\033[1m'
EOF_THEME
      ;;
    amber)
      cat <<'EOF_THEME'
export MQ_THEME_NAME="amber"
export MQ_COLOR_TITLE=$'\033[1;33m'
export MQ_COLOR_ERR=$'\033[0;31m'
export MQ_COLOR_OK=$'\033[0;33m'
export MQ_COLOR_WARN=$'\033[1;33m'
export MQ_COLOR_INFO=$'\033[0;37m'
export MQ_COLOR_BOLD=$'\033[1m'
EOF_THEME
      ;;
    ice)
      cat <<'EOF_THEME'
export MQ_THEME_NAME="ice"
export MQ_COLOR_TITLE=$'\033[1;36m'
export MQ_COLOR_ERR=$'\033[0;31m'
export MQ_COLOR_OK=$'\033[0;36m'
export MQ_COLOR_WARN=$'\033[1;37m'
export MQ_COLOR_INFO=$'\033[0;34m'
export MQ_COLOR_BOLD=$'\033[1m'
EOF_THEME
      ;;
    synth)
      cat <<'EOF_THEME'
export MQ_THEME_NAME="synth"
export MQ_COLOR_TITLE=$'\033[1;35m'
export MQ_COLOR_ERR=$'\033[0;31m'
export MQ_COLOR_OK=$'\033[0;36m'
export MQ_COLOR_WARN=$'\033[1;35m'
export MQ_COLOR_INFO=$'\033[0;35m'
export MQ_COLOR_BOLD=$'\033[1m'
EOF_THEME
      ;;
    *)
      return 1
      ;;
  esac
}

# Handles write theme file.
write_theme_file() {
  local theme="$1"
  {
    echo "# Generated by mq-theme-manager.sh"
    theme_exports "$theme"
  } > "$THEME_FILE"
}

# Shows current.
show_current() {
  if [[ -f "$THEME_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$THEME_FILE"
    echo "Current theme: ${MQ_THEME_NAME:-unknown}"
    echo "Theme file: $THEME_FILE"
  else
    echo "Current theme: default (no ~/.mq-theme file)"
  fi
}

# Handles preview theme.
preview_theme() {
  local theme="$1"

  if ! theme_description "$theme" >/dev/null 2>&1; then
    echo "Unknown theme: $theme" >&2
    exit 1
  fi

  (
    eval "$(theme_exports "$theme")"

    # Read by ui/terminal-ui/mq-ui.sh, which this script sources below.
    # ShellCheck cannot follow a source, so it sees assignments nothing reads.
    # shellcheck disable=SC2034
    APP_TITLE="MQ Theme Preview"
    # shellcheck disable=SC2034
    APP_SUBTITLE="$theme"
    # shellcheck disable=SC2034
    APP_AUTHOR="Author Mattias Camner"
    # shellcheck disable=SC2034
    BOX_INNER=88

    # shellcheck disable=SC1090
    source "$UI_LIB"

    print_header
    row_bold "THEME PREVIEW"
    empty_row
    row "Theme: $theme"
    row "Description: $(theme_description "$theme")"
    empty_row
    row "STATUS"
    row2 " ui_ok()" " success"
    row2 " ui_warn()" " warning"
    row2 " ui_err()" " error"
    row2 " row2()" " shared layout"
    empty_row
    ui_ok "OK message preview"
    ui_warn "Warning message preview"
    ui_err "Error message preview"
    print_footer
    pause_enter
  )
}

# Handles apply theme.
apply_theme() {
  local theme="$1"

  if ! theme_description "$theme" >/dev/null 2>&1; then
    echo "Unknown theme: $theme" >&2
    exit 1
  fi

  write_theme_file "$theme"
  echo "Applied theme: $theme"
  echo "Saved to: $THEME_FILE"
  if declare -f mq_theme_sync_counterpart >/dev/null 2>&1; then
    mq_theme_sync_counterpart "$theme" "$PROMPT_THEME_SCRIPT" "prompt"
  fi
  echo
  echo "Run one of these to see it:"
  echo "  mqlaunch"
  echo "  mqlaunch tweaks"
  echo "  ~/macos-scripts/ui/dashboards/mq-dashboard.sh"
}

# Handles reset theme.
reset_theme() {
  local mine theirs
  mine=""
  if [[ -f "$THEME_FILE" ]]; then
    mine="$(sed -n 's/^export MQ_THEME_NAME="\{0,1\}\([a-z]*\)"\{0,1\}$/\1/p' \
      "$THEME_FILE" | tail -1)"
  fi

  rm -f "$THEME_FILE"
  echo "Removed theme file."
  echo "UI will now use default colors."

  if declare -f mq_theme_reset_counterpart >/dev/null 2>&1; then
    theirs=""
    if [[ -x "$PROMPT_THEME_SCRIPT" ]]; then
      theirs="$(MQ_NO_TUI=1 "$PROMPT_THEME_SCRIPT" current 2>/dev/null \
        | sed -n 's/.*Current variant: *//p' | awk 'NF {print $1; exit}')"
    fi
    mq_theme_reset_counterpart "$mine" "$theirs" "$PROMPT_THEME_SCRIPT" "prompt"
  fi
}

# Prints usage information.
usage() {
  cat <<'USAGE'
mq-theme-manager.sh - manage terminal UI themes

Usage:
  mq-theme-manager.sh list
  mq-theme-manager.sh current
  mq-theme-manager.sh preview <theme>
  mq-theme-manager.sh apply <theme>
  mq-theme-manager.sh reset

Themes:
  classic
  green
  amber
  ice
  synth
USAGE
}

# Runs the main entry point.
main() {
  local cmd="${1:-list}"

  case "$cmd" in
    list)
      while read -r name; do
        [[ -z "$name" ]] && continue
        printf "%-10s %s\n" "$name" "$(theme_description "$name")"
      done < <(theme_list)
      ;;
    current)
      show_current
      ;;
    preview)
      [[ $# -ge 2 ]] || { usage; exit 1; }
      preview_theme "$2"
      ;;
    apply)
      [[ $# -ge 2 ]] || { usage; exit 1; }
      apply_theme "$2"
      ;;
    reset)
      reset_theme
      ;;
    help|-h|--help)
      usage
      ;;
    *)
      echo "Unknown command: $cmd" >&2
      echo
      usage
      exit 1
      ;;
  esac
}

main "$@"
