#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="${HOME}/macos-scripts"
UI_LIB="$BASE_DIR/ui/terminal-ui/mq-ui.sh"
THEME_FILE="${HOME}/.mq-theme"

theme_list() {
  cat <<'LIST'
classic
green
amber
ice
synth
LIST
}

theme_description() {
  case "$1" in
    classic) echo "Yellow/blue MQ default feel" ;;
    green)   echo "Green terminal vibe" ;;
    amber)   echo "Warm amber monitor feel" ;;
    ice)     echo "Cool cyan/blue theme" ;;
    synth)   echo "Purple neon style" ;;
    *)       return 1 ;;
  esac
}

theme_exports() {
  case "$1" in
    classic)
      cat <<'EOF_THEME'
export MQ_THEME_NAME="classic"
export MQ_COLOR_TITLE=$'\033[1;33m'
export MQ_COLOR_ERR=$'\033[0;31m'
export MQ_COLOR_OK=$'\033[0;32m'
export MQ_COLOR_WARN=$'\033[0;33m'
export MQ_COLOR_INFO=$'\033[0;34m'
export MQ_COLOR_BOLD=$'\033[1m'
EOF_THEME
      ;;
    green)
      cat <<'EOF_THEME'
export MQ_THEME_NAME="green"
export MQ_COLOR_TITLE=$'\033[1;32m'
export MQ_COLOR_ERR=$'\033[0;31m'
export MQ_COLOR_OK=$'\033[1;32m'
export MQ_COLOR_WARN=$'\033[0;33m'
export MQ_COLOR_INFO=$'\033[0;32m'
export MQ_COLOR_BOLD=$'\033[1m'
EOF_THEME
      ;;
    amber)
      cat <<'EOF_THEME'
export MQ_THEME_NAME="amber"
export MQ_COLOR_TITLE=$'\033[1;33m'
export MQ_COLOR_ERR=$'\033[0;31m'
export MQ_COLOR_OK=$'\033[0;33m'
export MQ_COLOR_WARN=$'\033[1;33m'
export MQ_COLOR_INFO=$'\033[0;37m'
export MQ_COLOR_BOLD=$'\033[1m'
EOF_THEME
      ;;
    ice)
      cat <<'EOF_THEME'
export MQ_THEME_NAME="ice"
export MQ_COLOR_TITLE=$'\033[1;36m'
export MQ_COLOR_ERR=$'\033[0;31m'
export MQ_COLOR_OK=$'\033[0;36m'
export MQ_COLOR_WARN=$'\033[1;37m'
export MQ_COLOR_INFO=$'\033[0;34m'
export MQ_COLOR_BOLD=$'\033[1m'
EOF_THEME
      ;;
    synth)
      cat <<'EOF_THEME'
export MQ_THEME_NAME="synth"
export MQ_COLOR_TITLE=$'\033[1;35m'
export MQ_COLOR_ERR=$'\033[0;31m'
export MQ_COLOR_OK=$'\033[0;36m'
export MQ_COLOR_WARN=$'\033[1;35m'
export MQ_COLOR_INFO=$'\033[0;35m'
export MQ_COLOR_BOLD=$'\033[1m'
EOF_THEME
      ;;
    *)
      return 1
      ;;
  esac
}

write_theme_file() {
  local theme="$1"
  {
    echo "# Generated by mq-theme-manager.sh"
    theme_exports "$theme"
  } > "$THEME_FILE"
}

show_current() {
  if [[ -f "$THEME_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$THEME_FILE"
    echo "Current theme: ${MQ_THEME_NAME:-unknown}"
    echo "Theme file: $THEME_FILE"
  else
    echo "Current theme: default (no ~/.mq-theme file)"
  fi
}

preview_theme() {
  local theme="$1"

  if ! theme_description "$theme" >/dev/null 2>&1; then
    echo "Unknown theme: $theme" >&2
    exit 1
  fi

  (
    eval "$(theme_exports "$theme")"

    APP_TITLE="MQ Theme Preview"
    APP_SUBTITLE="$theme"
    APP_AUTHOR="Author Mattias Camner"
    BOX_INNER=88

    # shellcheck disable=SC1090
    source "$UI_LIB"

    print_header
    row_bold "THEME PREVIEW"
    empty_row
    row "Theme: $theme"
    row "Description: $(theme_description "$theme")"
    empty_row
    row "STATUS"
    row2 " ui_ok()" " success"
    row2 " ui_warn()" " warning"
    row2 " ui_err()" " error"
    row2 " row2()" " shared layout"
    empty_row
    ui_ok "OK message preview"
    ui_warn "Warning message preview"
    ui_err "Error message preview"
    print_footer
    pause_enter
  )
}

apply_theme() {
  local theme="$1"

  if ! theme_description "$theme" >/dev/null 2>&1; then
    echo "Unknown theme: $theme" >&2
    exit 1
  fi

  write_theme_file "$theme"
  echo "Applied theme: $theme"
  echo "Saved to: $THEME_FILE"
  echo
  echo "Run one of these to see it:"
  echo "  mqlaunch"
  echo "  mqlaunch tweaks"
  echo "  ~/macos-scripts/ui/dashboards/mq-dashboard.sh"
}

reset_theme() {
  rm -f "$THEME_FILE"
  echo "Removed theme file."
  echo "UI will now use default colors."
}

usage() {
  cat <<'USAGE'
mq-theme-manager.sh - manage terminal UI themes

Usage:
  mq-theme-manager.sh list
  mq-theme-manager.sh current
  mq-theme-manager.sh preview <theme>
  mq-theme-manager.sh apply <theme>
  mq-theme-manager.sh reset

Themes:
  classic
  green
  amber
  ice
  synth
USAGE
}

main() {
  local cmd="${1:-list}"

  case "$cmd" in
    list)
      while read -r name; do
        [[ -z "$name" ]] && continue
        printf "%-10s %s\n" "$name" "$(theme_description "$name")"
      done < <(theme_list)
      ;;
    current)
      show_current
      ;;
    preview)
      [[ $# -ge 2 ]] || { usage; exit 1; }
      preview_theme "$2"
      ;;
    apply)
      [[ $# -ge 2 ]] || { usage; exit 1; }
      apply_theme "$2"
      ;;
    reset)
      reset_theme
      ;;
    help|-h|--help)
      usage
      ;;
    *)
      echo "Unknown command: $cmd" >&2
      echo
      usage
      exit 1
      ;;
  esac
}

main "$@"
